name: Build AppImage
on:
  workflow_dispatch:
  schedule:
    - cron: "5 */12 * * *"
  push:
    branches:
      - "main"

jobs:
  version:
    name: Postman AppImage Version
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      build: ${{ steps.check.outputs.build }}
    steps:
      - uses: actions/checkout@v2
      - name: Build Postman
        id: check
        run: |
          bash version.sh
  build:
    name: Postman AppImage Build
    needs: [version]
    if: ${{needs.version.outputs.build}} == 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Postman
        run: |
          bash build.sh
          echo "$POSTMAN_VERSION"
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: Postman.AppImage
          path: 'dist'
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Postman AppImage ${{ env.POSTMAN_VERSION }}
          automatic_release_tag: latest
          prerelease: false
          files: |
            dist/
          repo_token: ${{ secrets.GITHUB_TOKEN }}
